name: gelir_gider
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^4.3.2+2
  http: ^0.12.2
  theme_manager: ^1.0.4
  country_icons: ^1.1.1
  flutter_speed_dial: ^1.2.5
  pedantic: ^1.9.2
  date_time_picker: ^1.1.1
  intl: ^0.16.1
  sqflite: ^1.2.2
  gradient_app_bar: ^0.1.3
  percent_indicator: ^2.1.7+2
  shared_preferences: ^0.5.12+4
  custom_switch: ^0.0.1
  flutter_slider_drawer: ^1.2.1
  jiffy: ^3.0.1
  lite_rolling_switch: ^0.1.1
  google_fonts: ^1.1.2



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/flags/turkey.png
     - assets/flags/usa.png
     - assets/flags/china.png
     - assets/flags/germany.png
     - assets/flags/spain.png
     - assets/flags/arabia.png
     - assets/categories/bill.png
     - assets/categories/dues.png
     - assets/categories/entertainment.png
     - assets/categories/fix.png
     - assets/categories/food.png
     - assets/categories/health.png
     - assets/categories/hire.png
     - assets/categories/holiday.png
     - assets/categories/other.png
     - assets/categories/selfcare.png
     - assets/categories/shopping.png
     - assets/categories/education.png
     - assets/categories/
     - assets/flags/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  main_locale: en_US
  enabled: true
